### ISSUE TITLE
Export Controls

### ISSUE THREAD

**Issue by kemitchell** [polyformproject/commercial.polyformproject.org#4]
Add export controls compliance section to all variants.

**Comment by heathermeeker** [comment]
I agree, the license should be subject to the limitations of export controls.  (The open source carveout you added should handle any inconsistency with copyleft component licenses.) Probably also worth adding a "commercial software" government contracting provision, as those are useful in form agreements.

**Comment by kemitchell** [comment]
I have a FAR/DFAR recital in the current draft: https://github.com/polyformproject/commercial.polyformproject.org/blob/a5eb7c865bf938fbd0515ae251394bfa8e8109c0/terms.md#government-procurement

I'll add the usual on export controls when I can.

**Comment by kemitchell** [comment]
@heathermeeker what's your view on indemnities for breach of export-control obligations? If the customer exports without license, should they cover the vendor if the vendor gets roped into a regulatory kerfuffle?

**Comment by heathermeeker** [comment]
I don’t think you can indemnify for a violation of the law, butthere may be a distinction between a regulatory violation and an actual crime.
